// Generated by CoffeeScript 1.7.1
var addTotalToMenu, bigPurchases, highlightRow, mediumPurchases, otherPurchases, totalActivityCost;

totalActivityCost = function() {
  var total;
  total = 0;
  $('td.amount').each(function() {
    return total += parseFloat($(this).text().replace('$', ''));
  });
  return total;
};

bigPurchases = 0;

mediumPurchases = 0;

otherPurchases = 0;

highlightRow = function(amount) {
  bigPurchases = 0;
  mediumPurchases = 0;
  otherPurchases = 0;
  return $('td.amount').each(function() {
    amount = parseFloat($(this).text().replace('$', ''));
    if (amount >= 100.0) {
      bigPurchases += amount;
      return $(this).parent().css("background-color", 'red');
    } else if (amount >= 50.0) {
      mediumPurchases += amount;
      return $(this).parent().css("background-color", 'orange');
    } else {
      return otherPurchases += amount;
    }
  });
};

addTotalToMenu = function() {
  var totalHtml;
  $(".custom-totals").remove();
  totalHtml = "<tr class=\"custom-totals\">\n  <td class=\"left\">Total Activity Cost:</td>\n  <td>$" + (totalActivityCost()) + "</td>\n</tr>\n<tr class=\"custom-totals\">\n  <td class=\"left\">Total Big Purchases:</td>\n  <td>$" + bigPurchases + "</td>\n</tr>\n<tr class=\"custom-totals\">\n  <td class=\"left\">Total Medium Purchases:</td>\n  <td>$" + mediumPurchases + "</td>\n</tr>\n<tr class=\"custom-totals\">\n  <td class=\"left\">Total Other Purchases:</td>\n  <td>$" + otherPurchases + "</td>\n</tr>";
  return $('table.card-accountdetailcol > tbody:first > tr:nth-child(3)').after(totalHtml);
};

$(document).ready(function() {
  setTimeout(addTotalToMenu, 7000);
  return setTimeout(highlightRow, 5000);
});

$("#StatementPeriodQuick").on('change', function() {
  setTimeout(addTotalToMenu, 7000);
  return setTimeout(highlightRow, 5000);
});
