// Generated by CoffeeScript 1.7.1
var totalActivityCost;

totalActivityCost = function() {
  var total;
  total = 0;
  $('td.amount').each(function(i) {
    return total += parseFloat($(this).text().replace('$', ''));
  });
  return total;
};

$(document).ready(function() {
  return setTimeout(function() {
    var totalHtml;
    totalHtml = "<tr>\n  <td class=\"left\">Total Activity Cost:</td>\n  <td>$" + (totalActivityCost()) + "</td>\n</tr>";
    return $('table.card-accountdetailcol > tbody:first > tr:nth-child(3)').after(totalHtml);
  }, 5000);
});
