// Generated by CoffeeScript 1.7.1
var addTotalToMenu, highlightRow, totalActivityCost;

totalActivityCost = function() {
  var total;
  total = 0;
  $('td.amount').each(function() {
    return total += parseFloat($(this).text().replace('$', ''));
  });
  return total;
};

highlightRow = function(amount) {
  return $('td.amount').each(function() {
    amount = parseFloat($(this).text().replace('$', ''));
    if (amount >= 100.0) {
      return $(this).parent().css("background-color", 'red');
    } else if (amount >= 50.0) {
      return $(this).parent().css("background-color", 'orange');
    }
  });
};

addTotalToMenu = function() {
  var totalHtml;
  totalHtml = "<tr>\n  <td class=\"left\">Total Activity Cost:</td>\n  <td>$" + (totalActivityCost()) + "</td>\n</tr>";
  return $('table.card-accountdetailcol > tbody:first > tr:nth-child(3)').after(totalHtml);
};

$(document).ready(function() {
  setTimeout(addTotalToMenu, 5000);
  return setTimeout(highlightRow, 5000);
});
