// Generated by CoffeeScript 1.7.1
$(document).ready(function() {
  if (window.location.pathname !== '/') {
    $('#wrapper_header').hide();
    $('#bottomchapter').hide();
    return $('#wrapper_footer').hide();
  }
});
