return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "angular",
      "bash",
      "dockerfile",
      "eex",
      "elixir",
      "fish",
      "heex",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "ruby",
      "sql",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
