#!/bin/bash
set -o nounset

readonly DOTFILES_ROOT=$(pwd)

install_files() {
  files=$(ls $DOTFILES_ROOT | grep -v 'README.md' | grep -v 'script')

  for dotfile in $files
  do
    local destination="$HOME/.$dotfile"
    local target="$DOTFILES_ROOT/$dotfile"
    ln -sv "$target" "$destination"
  done
}

install_asdf() {
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  mkdir -p ~/.config/fish/completions; and cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
  asdf plugin-add python
  asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
  asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  asdf plugin-add rust https://github.com/asdf-community/asdf-rust.git
  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
}


install_files
