#!/bin/bash
set -o nounset

# Install Homebrew
install_homebrew() {
  /bin/bash -c "NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Add Homebrew to your PATH in /home/linuxbrew/.profile:
  if [[ $(uname) = "Linux" ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  elif [[ $(uname) = "Darwin" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  brew bundle
}

# Install chezmoi and apply dotfiles
install_files() {
  chezmoi init --apply --verbose achiurizo
}

# Install mise and languages. Also installs python latest for neovim plugins.
install_mise() {
  mise use -g python@latest
  mise use -g ruby@latest
  mise use -g ruby@latest
  pip install pynvim
}

install_tmux() {
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

install_homebrew
install_files
install_mise
