#!/bin/bash
set -o nounset

install_files() {
  files=$(ls $DOTFILES_ROOT | grep -v 'README.md' | grep -v 'script' | grep -v 'Brewfile' | grep -v 'screenshot.png')

  for dotfile in $files
  do
    local destination="$HOME/.$dotfile"
    local target="$DOTFILES_ROOT/$dotfile"

  done
}

install_fish() {
  sudo apt-add-repository ppa:fish-shell/release-3
  sudo apt-get update
  sudo apt-get install -y fish
  chsh -s /usr/bin/fish
}

install_packages() {
  sudo apt install -y build-essential curl git unzip tmux tig silversearcher-ag universal-ctags dirmngr libssl-dev make automake autoconf libncurses5-dev zlib1g-dev libffi-dev
}

install_asdf() {
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
  mkdir -p ~/.config/fish/completions; and cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
  asdf plugin-add python
  asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
  asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  asdf plugin-add rust https://github.com/asdf-community/asdf-rust.git
  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
}

install_neovim() {
  sudo apt install neovim
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim --headless +PlugInstall +UpdateRemotePlugins +qa
}

install_rust_packages() {
  asdf install rust latest
  asdf global rust $(asdf latest rust)
  cargo install exa bat jql ripgrep
}


install_fish
install_packages
install_asdf
install_rust_packages
install_neovim
