#!/bin/bash
set -o nounset

install_fish() {
  sudo apt-add-repository ppa:fish-shell/release-3
  sudo apt-get update
  sudo apt-get install -y fish
  chsh -s /usr/bin/fish
}

install_packages() {
  sudo apt install -y curl git unzip tmux tig silversearcher-ag universal-ctags dirmngr libssl-dev make automake autoconf libncurses5-dev
}

install_asdf() {
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
  mkdir -p ~/.config/fish/completions; and cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
  asdf plugin-add python
  asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
  asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
}

install_neovim() {
  sudo apt install neovim
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim --headless +PlugInstall +UpdateRemotePlugins +qa
}

install_fish
install_packages
install_asdf
install_neovim
