#!/bin/sh
# 
# Update the dotfiles and update all the submodules
git pull
git submodule init
git submodule update --depth 1
git submodule foreach git reset --hard
git submodule foreach git pull origin master
cd vim/bundle/vimproc.vim && make
